full_name = " ".join(str(input("ФИО:")).split())
parts = full_name.split()
initials = "".join([part[0].upper() for part in parts])
print(f"Инициалы: {initials}.")
print(f"Длина (символов): {len(full_name)}")
